### PR TITLE
Fix when magento is accessible only by full store url.

### PR DESCRIPTION
**Pull request by max-mi**
Fix when magento is accessible only by full store url.
Do nothing if 'index.php' exists in path, add it - if not.

### CODE REVIEW

**Comment by itirkarp** [comment]
Hi @max-mi, could you share some more information about this fix? Looks to me like it has not changed the behaviour that is currently in master.
/cc @zendesk/quokka

**Comment by adammw** [comment]
For reference we're internally tracking this at https://support.zendesk.com/agent/tickets/974628 and https://zendesk.atlassian.net/browse/OFFAPPS-383.

**Comment by max-mi** [comment]
Hello @itirkarp, there are two active ticket requests where the problem is in wrong path to Magento Zendesk API. It occurs when path to Magento Zendesk API looks like: http://somemagentourl.com/index.php/{storeurl}/zendesk/api/customers/{user_email}, but there is no option to make such link in Zendesk Magento App Settings, because it automatically appends 'index.php' at the end of the url string, for example if we paste following url into settings http://somemagentourl.com/index.php/storeurl/ we will have a request to http://somemagentourl.com/index.php/storeurl/index.php/zendesk/api/customers/{user_email} which is wrong and returns 404 (correct request url should be http://somemagentourl.com/index.php/storeurl/zendesk/api/customers/{user_email}). I suggest do not append 'index.php' if string already contains it.

Other issue connected with Zendesk Magento App is that in such implementation of connection there is no opportunity to get access to Magento Stores where guest access to store is restricted. (There is an option to use in-built magento API calls or maybe modify Magento Zendesk Integration module to catch requests before it will be processed by magento engine)

**Comment by itirkarp** [comment]
^ @danielbreves

**Comment by danielbreves** [comment]
:+1:, @max-mi I'll need a bit more context to help you with the second issue you mentioned. Have you submitted a ticket to support about it by any chance?

**Comment by jwswj** [comment]
:+1:

**Comment by jeremiahcurrier** [comment]
:+1:

**Comment by max-mi** [comment]
@danielbreves, I haven't submitted ticket. I'm supporting Magento Zendesk Integration which is connected with this app now. 
Second issue requires more complex modifications. I think the best method is to use REST API (OAuth authentication) of Magento, but this method has disadvantages:
1) On Magento server must be enabled rewriting module.
2) On Magento server must be installed cURL extension.
3) More complex application installation (Creating new API user, adding role, set rules) (but maybe it is possible to make it pragmatically, I should make a little research)
4) Client-side (Magento App) must implement OAuth authentication.
5) OAuth Rest API available only in Magento versions 1.7+

Also Magento Zendesk Integration Module should be modified:
1) Remove authorization logic. (There will be in-built OAuth)
2) Extend Magento Rest API by required methods.

**Comment by danielbreves** [comment]
@max-mi I'm not sure I understood it correctly, when would you need guest access to store?

**Comment by max-mi** [comment]
@danielbreves, here is example from ticket - http://burt.ubteam.co.nz

**Pull request merged**
